#!/usr/bin/env bash

# The MistralAI OCR process does not always leave a newline at the
# end of the output file. When concatenating, we stick a few extra
# blanks to ensure the files don't run together. This sometimes has
# the effect of breaking a paragraph that spans pages.

for file in $(cat /tmp/titles.txt); do
	echo $file
	uv run mistral-ocr --download-document "$file"
done 


